name: Format the code

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  format:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/format-stage.yaml@main
    secrets: inherit
